CREATE TABLE CONTROLLER
(
    ID          VARCHAR(36)  NOT NULL,
    PUBLISH_URI VARCHAR(100) NOT NULL,
    JAR_FILE_ID VARCHAR(36)  NOT NULL,
    CLASS_PATH  VARCHAR(100) NOT NULL,
    IS_ACTIVE   BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONTROLLER PRIMARY KEY (PUBLISH_URI)
);
