CREATE TABLE ENDPOINT
(
    ID          VARCHAR(36)  NOT NULL,
    PUBLISH_URL VARCHAR(100) NOT NULL,
    BEAN_NAME   VARCHAR(50)  NOT NULL,
    JAR_FILE_ID VARCHAR(36)  NOT NULL,
    CLASS_PATH  VARCHAR(100) NOT NULL,
    IS_ACTIVE   BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ENDPOINT PRIMARY KEY (PUBLISH_URL)
);

CREATE TABLE JAR_FILE
(
    ID         VARCHAR(36) NOT NULL,
    NAME       VARCHAR(40) NOT NULL,
    STATUS     CHAR        NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_JAR_FILE PRIMARY KEY (ID)
);

CREATE TABLE MOCK_RESPONSE
(
    ID               VARCHAR(36)  NOT NULL,
    PUBLISH_URL      VARCHAR(100) NOT NULL,
    METHOD           VARCHAR(50)  NOT NULL,
    CONDITION        TEXT         NOT NULL,
    RESPONSE_CONTENT TEXT,
    IS_ACTIVE        BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MOCK_RESPONSE PRIMARY KEY (PUBLISH_URL, METHOD, CONDITION)
);
